[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'kmnk/vim-unite-giti'

[[plugins]]
repo = 'vim-jp/vim-go-extra'
on_ft = 'go'

[[plugins]]
repo = 'dgryski/vim-godef'
on_ft = 'go'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'xolox/vim-session'
depends = ['/xolox/vim-misc']

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'Quramy/tsuquyomi'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'jason0x43/vim-js-indent'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'


[[plugins]]
repo = 'osyo-manga/vim-watchdogs'


